### PR TITLE
Adapt to weblate 5.6

### PR DESCRIPTION
**Pull request by sbidoul**
Recent versions of the weblate container [use uv to install weblate](https://github.com/WeblateOrg/docker/blob/65f04e38b31874ceb5626a3466b50ab640abda65/Dockerfile#L111-L117) and pip is not available in their venv.

@remi-filament

### CODE REVIEW

**Review by remi-filament — APPROVED** [review]
Thanks @sbidoul 
I realized they were using uv after sending you the e-mail.
I made the same changes on the server and tested it OK. Server is now running latest v5.6.2.

There are however a few local changes on docker-compose (healthcheck, extra_hosts) on server that have not been pushed to this repo. Let me know if you take them in consideration of if you would like me to ?

**Comment by sbidoul** [comment]
Cool! If you can push the docker-compose changes here that's welcome yes as I had forgotten.

**Comment by sbidoul** [comment]
BTW, another way would have been to use `pip --python /app/venv/bin/python install weblate-odoo-component-generator`, or `uv pip install --python /app/venv/bin/python`, as both pip and uv can work from outside the target venv these days.

**Comment by remi-filament** [comment]
Thanks for the tips !

**Pull request merged**
